twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      emergency:
        topic: /cmd_vel_emergency
        timeout: 0.5
        priority: 100
      sm:
        topic: /cmd_vel_sm
        timeout: 0.5
        priority: 50
      navigation:
        topic: /cmd_vel_nav
        timeout: 0.5
        priority: 10
