<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ijkbot_bringup</name>
  <version>0.1.0</version>
  <description>Верхнеуровневые launch-файлы для запуска мобильного робота IJKbot (Raspberry Pi 4B и Ноутбук)</description>
  <maintainer email="theodorrodionov@gmail.com">IJKbot Team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>depthimage_to_laserscan</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>image_transport_plugins</exec_depend>
  <exec_depend>sts3215_driver</exec_depend>
  <exec_depend>ijkbot_description</exec_depend>
  <exec_depend>ijkbot_nav2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

