depthimage_to_laserscan:
  ros__parameters:
    scan_height: 15              # Узкое окно строк (~1°), луч идет строго параллельно полу и не бьет в землю
    scan_time: 0.0667            # ~15 FPS (1/15 = 0.0667 с)
    range_min: 0.20              # Минимальная дистанция обнаружения (м)
    range_max: 2.00              # Максимальная дистанция (м) для исключения ложных препятствий от пола
    output_frame: "camera_link"  # Базовый фрейм лазерскана

