depthimage_to_laserscan:
  ros__parameters:
    scan_height: 10              # Узкий горизонтальный срез (±5 px от горизонта), лучи идут параллельно полу и не бьют в землю
    scan_time: 0.0667            # ~15 FPS (1/15 = 0.0667 с)
    range_min: 0.20              # Минимальная дистанция обнаружения (м)
    range_max: 4.00              # Максимальная дистанция (размер полигона 4x4 м)
    output_frame: "camera_link"  # Базовый фрейм лазерскана

